version: '3.7'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - webnet

  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - prisma-migrate
      - postgres
      - redis
    links:
      - redis
    networks:
      - webnet
    env_file:
      - .env

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - webnet

  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    networks:
      - webnet

volumes:
  postgres:
    name: nest-db

networks:
  webnet:
